Remove conditional deployment logic. (#10)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -27,61 +27,14 @@ jobs:
           docker-compose -f maintenance/docker-compose.yml config
           docker-compose -f security/docker-compose.local.yml config
 
-  create-changes-artifact:
-    name: Create Changes Artifact
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0 
-      
-      - name: Fetch main branch for comparison
-        run: git fetch origin main
-
-      - name: Check for changes in maintenance folder
-        id: maintenance_changes
-        run: |
-          if git diff --name-only $(git merge-base origin/main HEAD)..HEAD | grep -q '^maintenance/'; then
-            echo "Detected changes within the maintenance folder."
-            echo "maintenance_changes=true" >> folder_changes.txt
-          else
-            echo "No changes detected within the maintenance folder."
-            echo "maintenance_changes=false" >> folder_changes.txt
-          fi
-
-      - name: Check for changes in security folder
-        id: security_changes
-        run: |
-          if git diff --name-only $(git merge-base origin/main HEAD)..HEAD | grep -q '^security/'; then
-            echo "Detected changes within the security folder."
-            echo "security_changes=true" >> folder_changes.txt
-          else
-            echo "No changes detected within the security folder."
-            echo "security_changes=false" >> folder_changes.txt
-          fi
-
-      - name: Upload changes artifact
-        uses: actions/upload-artifact@v4
-        with:
-          name: changes-artifact
-          path: |
-            folder_changes.txt
-
   deploy:
     name: Deploy Docker Compose Files
     runs-on: ubuntu-latest
-    needs: [validate-docker-compose , create-changes-artifact]
+    needs: [validate-docker-compose]
     if: github.ref == 'refs/heads/main'
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
-
-      - name: Download artifacts
-        uses: actions/download-artifact@v4
-        with:
-          name: changes-artifact
-          path: ./artifacts
 
       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.9.0
@@ -102,44 +55,33 @@ jobs:
       - name: Deploy security changes
         id: deploy_security_changes
         run: |
-          # Load the security_changes value from the artifact file
-          if grep -q 'security_changes=true' ./artifacts/folder_changes.txt; then
-            echo "Security folder has changes. Proceeding with deployment."
-            ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
 
-            for file in security/certbot.sh security/docker-compose.yml; do
-              scp -o StrictHostKeyChecking=no $file ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/security
+          for file in security/certbot.sh security/docker-compose.yml; do
+            scp -o StrictHostKeyChecking=no $file ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/security
 
-              if [ $? -eq 0 ]; then
-                echo "Security file transferred for $file successfully."
-              else
-                echo "Error transferring security file for $file."
-                exit 1
-              fi
-            done
-          else
-            echo "No changes in security folder. Skipping deployment."
-          fi
+            if [ $? -eq 0 ]; then
+              echo "Security file transferred for $file successfully."
+            else
+              echo "Error transferring security file for $file."
+              exit 1
+            fi
+          done
 
       - name: Deploy maintenance changes
         id: deploy_maintenance_changes
         run: |
           # Load the maintenance_changes value from the artifact file
-          if grep -q 'maintenance_changes=true' ./artifacts/folder_changes.txt; then
-            echo "Maintenance folder has changes. Proceeding with deployment."
-            ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
-            scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
-                maintenance/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/maintenance/
+          ssh-keyscan -t ed25519 ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
+          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 \
+              maintenance/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/srv/app/site-reliability-tools/maintenance/
 
-            # Check if the scp command was successful
-            if [ $? -eq 0 ]; then
-              echo "Maintenance file transferred for docker-compose.yml successfully."
-            else
-              echo "Error transferring maintenance file for docker-compose.yml."
-              exit 1
-            fi
+          # Check if the scp command was successful
+          if [ $? -eq 0 ]; then
+            echo "Maintenance file transferred for docker-compose.yml successfully."
           else
-            echo "No changes in maintenance folder. Skipping deployment."
+            echo "Error transferring maintenance file for docker-compose.yml."
+            exit 1
           fi
 
       - name: Update Docker Swarm service
